### ISSUE TITLE
Fix CREATE2 salt interpolation in multi-chain deployment script

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#750] opened 2023-12-17 17:26 UTC
Here: https://github.com/sablier-labs/v2-core/blob/79aa953330c00fdb5a8a588cf65526008567df0f/shell/deploy-multi-chain.sh#L178

I've tried all of the following approaches. None worked:

| Approach | Result in Terminal |
|--------|--------|
| Surround with `\"` | `'"ChainID' 43114, Version '1.1.1"'` |
| Surround with `\'` | `'\'\''ChainID' 43114, Version '1.1.1\'\'''` |
| Surround with `'` | `''\''ChainID' 43114, Version '1.1.1'\'''` | 
| Surround with `'` | Broken script | 

What should be generated is this:

```
"ChainID 43114, Version 1.1.1"
```

Or this:

```
'ChainID 43114, Version 1.1.1'
```

Note: this is best debugged by adding the `-x` flag here:

```sh
$ set -euxo pipefail
```

**Comment by smol-ninja** [comment] 2023-12-17 19:33
Interestingly, it works for v2-periphery. When I was polishing these scripts, even I couldn't manage to make it work for v2-core while it works totally fine for v2-periphery. Although everything looks same including the foundry version (may be I am missing something). Did you try to run the script for v2-periphery with --deterministic flag?

<img width="400" alt="Screenshot 2023-12-17 at 19 30 25" src="https://github.com/sablier-labs/v2-core/assets/6676622/ed630fb6-57a3-4de4-9591-d0c20df5d0ca">

**Comment by PaulRBerg** [comment] 2023-12-18 07:59
Interesting. I haven't run the script in V2 Periphery just yet.

**Comment by smol-ninja** [comment] 2023-12-18 14:18
I managed to fix this issue from our end. See PR: https://github.com/sablier-labs/v2-core/pull/753. There was an issue with our deployment script. 

Bash is very smart to interpret string as executable command. Expanding string using multi line comments doesn't work as intended sometimes. Source https://google.github.io/styleguide/shellguide.html#arrays. Every ChatGPT wasn't of much use here.

I tried every combination and it was considering `'ChainID $chain_id, Version 1.1.1'` as either without quote or `'ChainID' $chain_id, Version '1.1.1'`. This is because of how bash treats string while executing commands through scripting. Google styleguide recommends to avoid use of strings for sequences.

It works now, I tested locally but now there is another issue with foundry. Foundry is throwing error when comma is present in the salt string. See screenshots below.

Without comma:

<img width="861" alt="Screenshot 2023-12-18 at 14 16 50" src="https://github.com/sablier-labs/v2-core/assets/6676622/f22825fd-c7e2-4417-8e0b-fbb77e4edd17">

With comma:

<img width="857" alt="Screenshot 2023-12-18 at 14 17 02" src="https://github.com/sablier-labs/v2-core/assets/6676622/b456dedc-31a8-4e0b-aba2-767d9ebf5ea3">

That means https://github.com/foundry-rs/foundry/issues/6265#issuecomment-1859217485 is a legit issue. It was not a false alarm @PaulRBerg

**Comment by smol-ninja** [comment] 2023-12-18 18:37
Update
------
It was not even working in v2-periphery correctly. The create2Salt was interpreted as '\'\''ChainID' 11155111, Version '1.1.0\'\'''. Fixed in https://github.com/sablier-labs/v2-periphery/pull/240.

but the issue mentioned above remains the same. It does not work even in periphery for "ChainID 11155111, Version 1.1.1" but works for other variations such as "ChainID 11155110, Version 1.1.1" or "ChainID 11155111 , Version 1.1.1".

@PaulRBerg for now, I'd recommend to use a slightly different salt such as "ChainID 11155111 , Version 1.1.1".

**Closed** 2023-12-22 14:10 UTC
Labels: bug, priority2

**Comment by PaulRBerg** [comment] 2023-12-23 18:29
Nice finding with the Google styleguide!
