### ISSUE TITLE
Add a `shared` dir in tests for common functions between merkle lockup contracts

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#1001] opened 2024-05-07 20:00 UTC
Ref https://github.com/sablier-labs/v2-core/issues/1000#issuecomment-2259313830

The idea is to do something similar to how core tests are structured: https://github.com/sablier-labs/v2-core/tree/staging/test/core/integration/concrete/lockup

**Comment by smol-ninja** [comment] 2024-07-30 22:35
Duplicate of https://github.com/sablier-labs/v2-core/issues/1002.

**Closed by smol-ninja** 2024-07-30 22:35 UTC
Labels: type: test, work: clear, priority: 3, effort: medium
