### ISSUE TITLE
Inconsistency in the order of parameters in structs between LockupLinear and LockupDynamic

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-core#728] opened 2023-11-24 13:54 UTC
We should have a consistent order of parameter structs:

- Sender
- Recipient
- Total Amount
- Asset
- Cancelable
- Transferable
- Time-related variables
- Broker

LD:

https://github.com/sablier-labs/v2-core/blob/e1a53b4c839912573996c313d447aeeed6eb434c/src/types/DataTypes.sol#L111-L121

LL:

https://github.com/sablier-labs/v2-core/blob/e1a53b4c839912573996c313d447aeeed6eb434c/src/types/DataTypes.sol#L223-L232

**Comment by PaulRBerg** [comment] 2023-11-30 15:46
Isn't the difference due to gas efficiency reasons?

**Comment by andreivladbrg** [comment] 2023-11-30 16:41
These structs the ones passed in the `create` functions, the order of loading parameters in the stack does not affect the gas prices. Let's not confuse with the storage `Stream` structs

**Comment by PaulRBerg** [comment] 2023-11-30 16:46
That's fair - an explanation in the OP would have been helpful

**Comment by PaulRBerg** [comment] 2024-01-01 16:16
Closing as a duplicate of #772.

**Comment by PaulRBerg** [comment] 2024-01-04 13:05
Pasting @smol-ninja's comment from [here](https://github.com/sablier-labs/v2-core/issues/772#issuecomment-1874206671):

> If I may answer your answer @PaulRBerg, since struct CreateWithDurations is only used in memory or on the stack (and never storage), the order of parameters does not affect gas usage. Each variable has its own slot.
>
> So ordering does not matter here.

**Closed** 2024-01-12 12:58 UTC
Labels: type: refactor, work: clear, priority: 3, effort: medium
