### ISSUE TITLE
Write a multi-chain source code verify script

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#749] opened 2023-12-17 17:15 UTC
Similar to the multi-chain deployment script written by @andreivladbrg and polished by @smol-ninja, we should also write a multi-chain verification script.

It is often the case that the verification part fails in a `forge script` command (example [here](https://github.com/foundry-rs/foundry/issues/6050#issuecomment-1859224976)).

Having to manually verify each contract is a chore.

**Comment by smol-ninja** [comment] 2023-12-19 16:21
The issue is not related to verification but to the RPC endpoint.

The following command with also throw the "Deserialization Error: EOF while parsing a value at line 1 column 0."
```bash
FOUNDRY_PROFILE=optimized \
forge script script/DeployDeterministicCore3.s.sol \
--rpc-url "https://bnbsmartchain-mainnet.infura.io/v3/68967a55fb91488684a9c1000f321d7f" \
--sig "run(string,address,address,uint256)" "ChainID 56, Version 1.1.1" 0x6666cA940D2f4B65883b454b7Bc7EEB039f64fa3 0x33511f69A784Fd958E6713aCaC7c9dCF1A5578E8 300 \
-vvv
```

Instead of writing a separate script for verification, we can add checks in the `deploy-multi-chain.sh` and `generate-deployment-command.sh` scripts. It can simulate the deployment and if there is an error, we can display it. Deployment will not continue until there are errors.

**Comment by smol-ninja** [comment] 2023-12-24 01:32
I think we can close this issue. The issue is related to RPC endpoint and not related to verification process. I recently tried multiple deployments and all of them got verified automatically. The latest script is able to handle such errors easily PR https://github.com/sablier-labs/v2-core/pull/752

1. https://sepolia.etherscan.io/address/0x54888671ee181afc5ab3b1a7ed0c46e8bf10760c#code
2. See all deployments: https://sepolia.etherscan.io/address/0xeaf39695973254d21c8956037c0baf5fdda92ec6

**Closed by smol-ninja** 2023-12-24 01:32 UTC
Labels: feature, priority3

**Comment by PaulRBerg** [comment] 2023-12-24 13:58
I don't see how the deployment simulation helps with errors related to RPC endpoints. And also, there are verification-specific issues (such as the recent debacle with [via IR](https://twitter.com/PaulRBerg/status/1737169159052468479)).

But anyway, I'm happy to close this issue on the basis that we're not frequently making deployments, and this script wouldn't be needed that often.
